### PR TITLE
Improved use of memory in ScreenPlotter, some bug fixes and an enhancement

### PR DESCRIPTION
**Pull request by kevinjwalters**
The `plotters_combined` example dies with a `MemoryError` on a Feather nRF52840 Express with a PMS5003 attached to an Enviro+ FeatherWing. These changes address this.

- The ScreenPlotter now uses a fixed size circular buffer which is allocated once to reduce the amount of list operations - this should improve memory fragmentation which can be a serious problem on MicroPython/CircuitPython due to lack of compaction in GC. The value data no longer used (scrolled off screen) will still be GC'd. #19
- Pixel undraw code was broken for overlapping pixels, noticeable on some multi-line plots #22
- New arguments to constructor `width=None, height=None, extra_data=16, auto_show=True, auto_discard=True` #19 #23
  - width and height can now be specified or will default to screen values
  - `extra_data` is how many data_points are stored beyond those on the screen for efficient redrawing and allowing user program to jump scroll if desired.
  - `auto_show` allows the display.show to be disabled to allow a program more control and efficient use via `object.group`
  - `auto_discard` determines what happens if more data_points are added than `extra_data` without calling `draw()` - a `False` value will raise an exception.
- inhibits automatic screen refresh during bitmap update for minor efficiency improvements #23
- Clearing the bitmap now uses the more efficient `fill()` introduced in CircuitPython 5.3.0 #23
- New `plotter_test.py` to aid testing with visual verification and checking performance
 
Tested with `plotters_combined.py` and `plotter_test.py` on Feather nRF52840 Express with `6.0.0`. 
 - `plotters_combined` runs fine with PMS5003 in `passive` mode for at least 12.5hrs at `interval = 0.2` (code floors at 1s) based on testing. It starts around 53k free memory and stays constant at 30k once it starts scrolling.
 - `plotters_combined` runs fine with PMS5003 in `active` mode for at least 5hrs, rest is same as above.

No dependency on #21 but that could be reviewed at same time as this and applied beforehand.

### CODE REVIEW

**Comment by kevinjwalters** [comment]
@dglaude This looks good if you wish to test on your FeatherS2 setup with Enviro+ FeatherWing and PMS5003. This goes with the standard Pimoroni setup described in https://www.instructables.com/Using-the-Pimoroni-Enviro-FeatherWing-With-the-Ada/ and https://github.com/pimoroni/pms5003-circuitpython/pull/8

**Comment by kevinjwalters** [comment]
@Gadgetoid This together with https://github.com/pimoroni/pms5003-circuitpython/pull/8 makes the Enviro+ FeatherWing more robust and more memory efficient, let me know what you think.

If/when this is all applied it would be great to get a refresh of submodules and a new release for this.

**Comment by kevinjwalters** [comment]
I've half broken the page turning for `plotters_combined` when interval isn't 1 second. I'll fix this up in a day or two. FIXED with https://github.com/pimoroni/EnviroPlus-FeatherWing/pull/24/commits/0c2cf96455fc9a396bd7e444d476503bfd2230c6

**Comment by kevinjwalters** [comment]
I've effectively tested this on 6.2.0 too while developing support for SCD-30 CO2 sensor.

**Comment by kevinjwalters** [comment]
@Gadgetoid If you've got the FeatherWing out you might want to review the four outstanding (in every respect) PRs for this repo.

**Comment by Gadgetoid** [comment]
Of course I attempted to merge the other, smaller PRs and made a total hash of things- conflicting this PR.

Sorry for the lack of response here, I've been totally overwhelmed with a mixture of life and the million other things vying for my attention.

I think I've got an EnviroPlus FeatherWing that survived my move down-south somewhere, but your incredible level of diligence here makes me extremely tempted just to merge :smile: (I don't have more than one Feather board to test with at the moment :grimacing:)

**Comment by kevinjwalters** [comment]
I did a lot of testing but it's always possible to miss something. That was all pre CircuitPython 7 and only on Feather nRF52840. Worth giving it all a go on an M4 board with CPy 7.

**Comment by Gadgetoid** [comment]
Okay, merge conflict fixed!

I say we do or die with this :rocket:

Oh and- thank you, very much! This project is a little bit on the fringe of my knowledge so it's difficult to keep things tip top, though I'm slowly starting to work more generally with CircuitPython.

**Pull request merged**
