### PR TITLE
Two new example programs to plot CO2 data from Sensirion SCD-30 using Adafruit libraries

### PR DESCRIPTION
**Pull request by kevinjwalters**
Two new programs for #25 to plot CO2 from (Adafruit) Sensirion SCD-30 using https://github.com/adafruit/Adafruit_CircuitPython_SCD30 library.

 - `examples/plotter_scd30.py` - plot up to 3000ppm. 1b95f08f60282727a4482948d7bbb395cbe6ada2 064cb2564ef402e1ec738afb02020a33725feba3
 - `examples/plotters_combined_with_scd30.py` - fourth optional plot page based on the `adafruit_scd30` library being present and the `SCD30` object initialises ok, i.e. device is plugged in and responding over i2c. This version also passes the pressure to the SCD-30. 5af87611c242bd68ea7396c502ff84257e08e719 8e5377a40c825a8359e67b8765b55605f53d455b

The combined one is a new file rather put all the functionality into `plotters_combined.py` as that's getting a little large in memory usage terms and SCD-30 users are probably in the minority.

Tested on a Feather nRF52840 Express running 6.2.0 and brand new Enviro+ FeatherWing: [Plotting Carbon Dioxide concentration with Enviro+ FeatherWing and Sensirion SCD-30 NDIR Sensor](https://www.youtube.com/watch?v=Szn-ZCr0kYg) (YouTube).

https://github.com/pimoroni/EnviroPlus-FeatherWing/pull/26/commits/288953d6001538370d0e829b3f4828a81c74e31c is same type of bugfix as https://github.com/pimoroni/EnviroPlus-FeatherWing/pull/24/commits/0c2cf96455fc9a396bd7e444d476503bfd2230c6

### CODE REVIEW

**Comment by kevinjwalters** [comment]
I'll update the REFERENCE.md file when #20 is approved and applied.

**Comment by kevinjwalters** [comment]
The SCD-30 library supports passing the pressure and since this is available from the BME280 I added that to `plotters_combined_with_scd30.py`.

**Comment by kevinjwalters** [comment]
Can be seen in action on [Instructables: Plotting Carbon Dioxide Levels With the Pimoroni Enviro+ FeatherWing and Adafruit SCD-30](https://www.instructables.com/Plotting-Carbon-Dioxide-Levels-With-the-Pimoroni-E/).

**Comment by Gadgetoid** [comment]
Again, sorry for the radio silence here. This effort is very, very much appreciated.

**Pull request merged**
